{{- if .Values.gateway.enabled -}}
{{- $fullName := include "go-app-chart.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  {{- if .Values.gateway.staticIpName }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.staticIpName }}
  {{- end }}
{{- end }}